theme: jekyll-theme-cayman
title: Tom Krumpolc
description: Welcome to my homepage. Here you can learn more about my research, personal projects, and interests.
markdown: kramdown
include:
  - "_img"
owner:
  name: Tom Krumpolc
  avatar: /_photos/Headshot.jpg
  

